"use client";
export const Personal = {
	name: "Habibur Rahman.",
	title: "I build things for web.",
	image: "/20230207_092250.jpg",
	desc: "I am a web developer with 4+ years of experience in React. I have a strong fundation in frontend & back-end development and am skilled in creating user-friendly and responsive web applications using React and its ecosystem. ",
	about: "I am a web developer with 4+ years of experience in React. I have a strong fundation in frontend & back-end development and am skilled in creating user-friendly and responsive web applications using React and its ecosystem. I am a web developerwith 4+ years of experience I am a web developer with 4+ years of experience in React. I have a strong fundation in frontend & back-end development and am skilled in creating user-friendly and responsive web applications using React and its ecosystem. I am a web developerwith 4+ years of experience I am a web developer with 4+ years of experience in React. I have a strong fundation in frontend & back-end development developerwith 4+ years of experience ",
};

export const Technologies = [
	"JavaScript(ES6+)",
	"React",
	"TypeScript",
	"MongoDB",
	"Next.js",
	"React Native",
	"Node.js",
	"Express.js",
	"Tailwindcss",
];

export const WorkExperience = [
	{
		company: "ReactBD",
		post: "Engineer",
		duration: " Jan 2023 - Present",
		works: [
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
		],
	},
	{
		company: "Google",
		post: "Engineer",
		duration: " Jan 2023 - Present",
		works: [
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
		],
	},
	{
		company: "Apple",
		post: "Engineer",
		duration: " Jan 2023 - Present",
		works: [
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
		],
	},
	{
		company: "Amazon",
		post: "Engineer",
		duration: " Jan 2023 - Present",
		works: [
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
			"Write modern,preformant, maintainable code for a diverse array of client and internal project",
		],
	},
];

export const TopProjects = [
	{
		title: "Amazonn Clone 2.0",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus incidunt exercitationem, natus corporis est 0-auth suscipit, aliquam doloribus tenetur eligendi, culpa esse a? Repellendus quidem dolorem sapiente dolor iusto saepe accusamus! strip",
		image: "/1.png",
		technologies: [
			"NextJs",
			"TypeScript",
			"Next-auth",
			"Vercel",
			"Deployment",
		],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Amazonn Clone 2.0",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus incidunt exercitationem, natus corporis est 0-auth suscipit, aliquam doloribus tenetur eligendi, culpa esse a? Repellendus quidem dolorem sapiente dolor iusto saepe accusamus! strip",
		image: "/1.png",
		technologies: [
			"NextJs",
			"TypeScript",
			"Next-auth",
			"Vercel",
			"Deployment",
		],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Amazonn Clone 2.0",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus incidunt exercitationem, natus corporis est 0-auth suscipit, aliquam doloribus tenetur eligendi, culpa esse a? Repellendus quidem dolorem sapiente dolor iusto saepe accusamus! strip",
		image: "/cat2.PNG",
		technologies: [
			"NextJs",
			"TypeScript",
			"Next-auth",
			"Vercel",
			"Deployment",
		],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Amazonn Clone 2.0",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus incidunt exercitationem, natus corporis est 0-auth suscipit, aliquam doloribus tenetur eligendi, culpa esse a? Repellendus quidem dolorem sapiente dolor iusto saepe accusamus! strip",
		image: "/cat2.PNG",
		technologies: [
			"NextJs",
			"TypeScript",
			"Next-auth",
			"Vercel",
			"Deployment",
		],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
];

export const ArchiveProjects = [
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel", "React"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
];
export const ArchiveMoreProjects = [
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel", "React"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel", "React"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
	{
		title: "Educare English Learning Academy",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Consequatur, cumque enim. Possimus quasi enim, suscipitculpa delectus",
		technologies: ["NextJs", "TypeScript", "Vercel"],
		github: "www.github.com/habibthealien",
		open: "www.sweet16th.natlify.app",
	},
];
